data:
  path: "/data/file.nc"
layers:
  - figure:
      size: [1200, 700]
  - type: Axis
    position: [1, 1]
    attributes:
      aspect: DataAspect
    plots:
      - type: image
        attributes:
          colormap: viridis
        args: [[1, 2]]
